---
- hosts: target
  tasks:
          - name: Install EPEL release
            yum:
                    name: epel-release
                    state: latest
            become: yes
            become_method: sudo

          - name: Install Python3.6 from EPEL
            yum:
                    name:
                            - python36
                            - python36-devel
                            - python-devel
                            - python36-setuptools
                            - python3-pip
                            - python-setuptools
                            - python36-cffi
                            - libyaml
                            - libyaml-devel
                    state: latest
            when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int < 8
            become: yes
            become_method: sudo

          - name: Install Python3.6 from EPEL
            yum:
                    name:
                            - python3
                            - python3-devel
                            - python3-setuptools
                            - python3-pip
                            - python3-cffi
                            - libyaml
                            - libyaml-devel
                    state: present
                    enablerepo: "PowerTools"
            when: ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 8
            become: yes
            become_method: sudo
