---
- name: Delete build dirs openblas
  file:
          path: "{{ item }}"       
          state: absent
  with_items:
          - "{{ openblas_dir_base }}"
          - "{{ openblas_dir_src }}"
          - "{{ openblas_dir_output }}"
          - "{{ dir_rpmbuild_sources }}"

- name: Create build dirs openblas
  file:
          path: "{{ item }}"       
          state: directory
          mode: '0755'
          owner: "{{ user }}"
          group: "{{ user }}"
  with_items:
          - "{{ openblas_dir_base }}"
          - "{{ openblas_dir_src }}"
          - "{{ openblas_dir_output }}"
          - "{{ dir_rpmbuild_sources }}"

- name: Fetch rpm spec for openblas
  template:
          src: "openblas.spec.j2"
          dest: "{{ openblas_dir_src }}/openblas.spec"
          owner: "{{ user }}"
          group: "{{ user }}"
  when: use_openhpc == true 

- name: Fetch rpm spec for openblas
  template:
          src: "openblas_upstream.spec.j2"
          dest: "{{ openblas_dir_src }}/openblas.spec"
          owner: "{{ user }}"
          group: "{{ user }}"
  when: use_openhpc == false 

- name: Fetch rpm spec for openblas
  template:
          src: "{{ item }}"
          dest: "{{ dir_rpmbuild_sources }}/{{ item }}"
          owner: "{{ user }}"
          group: "{{ user }}"
  with_items:
          - "openblas-0.2.15-system_lapack.patch"
          - "openblas-0.2.5-libname.patch"
          - "openblas-0.2.15-constructor.patch"
          - "openblas-0.3.3-noopt.patch"
  when: use_openhpc == false 
          
- name: Fetch openblas release tarball
  get_url:
          url: "{{ openblas.release_url }}"
          dest: "{{ dir_rpmbuild_sources }}/openblas-develop.zip"

- name: Fetch ohpc build deps for openblas
  get_url:
          url: "{{ item }}"
          dest: "{{ dir_rpmbuild_sources }}/{{ item | basename }}"
  with_items:
          - "{{ ohpc_raw_github_baseurl }}/components/OHPC_compiler_deps"
          - "{{ ohpc_raw_github_baseurl }}/components/OHPC_macros"
          - "{{ ohpc_raw_github_baseurl }}/components/OHPC_mod_generator.sh"
          - "{{ ohpc_raw_github_baseurl }}/components/OHPC_setup_compiler"
          - "{{ ohpc_raw_github_baseurl }}/components/OHPC_setup_mpi"
          - "{{ ohpc_raw_github_baseurl }}/components/serial-libs/openblas/SOURCES/fix-arm64-cpuid-return.patch"
          - "{{ ohpc_raw_github_baseurl }}/components/serial-libs/openblas/SOURCES/openblas-libs.patch"
          - "{{ ohpc_raw_github_baseurl }}/components/serial-libs/openblas/SOURCES/openblas-noexecstack.patch"
          - "{{ ohpc_raw_github_baseurl }}/components/serial-libs/openblas/SOURCES/rpmlintrc"
  when: use_openhpc == true 

- name: Build openblas
  shell: "rpmbuild -ba {{ openblas_dir_src }}/openblas.spec"
  args:
          chdir: "{{ openblas_dir_src }}"
          executable: "/bin/bash"
  register: openblas_build_log
- debug: var=openblas_build_log

- name: Create Repo in rpmbuild/RPMS
  shell: "createrepo {{ dir_rpmbuilt }}"
  become: yes
  become_user: root
  become_method: sudo
