---
arch: "aarch64"
distribution: "el{{ ansible_distribution_major_version|int }}"

python3: "/usr/bin/python3"
user: "builder"
build_id: "42"
dir_root: "/home/{{ user }}/{{ build_id }}"
dir_home: "{{ dir_root }}/tensorflow_build"
dir_repo: "{{ dir_root }}/repo_tensorflow"
dir_built: "{{ dir_root }}/built_tarballs"
venv_path: "{{ dir_root }}/virtualenv"
use_openhpc: "{{ true if ansible_os_family == 'RedHat' and ansible_distribution_major_version|int < 8 else false }}"

# rpm build variables
dir_rpmbuilt: "/home/{{ user }}/rpmbuild/RPMS/{{ arch }}"
dir_rpmbuild_sources: "/home/{{ user }}/rpmbuild/SOURCES/"

# OHPC Variables
ohpc_raw_github_baseurl: "https://raw.githubusercontent.com/openhpc/ohpc/obs/OpenHPC_1.3.9_Factory"

ohpc_toolchain_base_dir: "/opt/ohpc/pub/compiler/gcc/8.3.0"
ohpc_toolchain_bin_dir: "/opt/ohpc/pub/compiler/gcc/8.3.0/bin"
ohpc_toolchain_lib_dir: "{{ ohpc_toolchain_base_dir }}/lib64"
ohpc_toolchain_include_dir: "{{ ohpc_toolchain_base_dir }}/include"

toolchain_base_dir: "{{ ohpc_toolchain_base_dir if use_openhpc == true else '/usr/bin/' }}"
toolchain_bin_dir: "{{ ohpc_toolchain_bin_dir if use_openhpc == true else toolchain_base_dir }}"
toolchain_lib_dir: "{{ ohpc_toolchain_lib_dir if use_openhpc == true else '/usr/lib64/' }}"
toolchain_include_dir: "{{ ohpc_toolchain_include_dir if use_openhpc == true else '/usr/include/' }}"

_openblas_library_path: "/opt/ohpc/pub/libs/gnu8/openblas/{{ openblas_version if build_openblas == true else openhpc_openblas_version }}/lib"
_openblas_include_path: "/opt/ohpc/pub/libs/gnu8/openblas/{{ openblas_version if build_openblas == true else openhpc_openblas_version }}/include"

openblas_library_path: "{{ _openblas_library_path if use_openhpc == true else toolchain_lib_dir }}"
openblas_include_path: "{{ _openblas_include_path if use_openhpc == true else toolchain_include_dir }}"


_fftw_library_path: "/opt/ohpc/pub/libs/gnu8/openmpi3/fftw/3.3.8/lib"
_fftw_include_path: "/opt/ohpc/pub/libs/gnu8/openmpi3/fftw/3.3.8/include"

fftw_library_path: "{{ _fftw_library_path if use_openhpc == true else toolchain_lib_dir }}"
fftw_include_path: "{{ _fftw_include_path if use_openhpc == true else toolchain_include_dir }}"


_hdf5_base_path: "/opt/ohpc/pub/libs/gnu8/hdf5/1.10.5"
_hdf5_library_path: "{{ _hdf5_base_path }}/lib"
_hdf5_include_path: "{{ _hdf5_base_path }}/include"

hdf5_base_path: "{{ _hdf5_base_path if use_openhpc == true else toolchain_lib_dir }}"
hdf5_include_path: "{{ _hdf5_include_path if use_openhpc == true else toolchain_include_dir }}"
hdf5_library_path: "{{ _hdf5_library_path if use_openhpc == true else toolchain_lib_dir }}"


_mpi_base_path: "/opt/ohpc/pub/mpi/openmpi3-gnu8/3.1.4"
_mpi_library_path: "{{ _mpi_base_path }}/lib"

mpi_base_path: "{{ _mpi_base_path if use_openhpc == true else '/usr/lib64/openmpi/' }}"
mpi_library_path: "{{ _mpi_library_path if use_openhpc == true else '/usr/lib64/openmpi/lib' }}"


LD_LIBRARY_PATH: "{{ hdf5_library_path }}:{{ openblas_library_path }}:{{ mpi_library_path }}:{{ toolchain_lib_dir }}"
LD_INCLUDE_PATH: "{{ hdf5_include_path }}:{{ openblas_include_path }}:{{ mpi_base_path }}/include:{{ toolchain_include_dir }}"

### BUILD DEPENDENCIES
# Non OHPC, non python, non java
tf_build_dependencies:
        - "@Development Tools"
        - cmake
        - createrepo
        - rpm-build
        - vim
        - wget
        - unzip
        - tar
        - redhat-lsb-core

ohpc_release_url: "http://build.openhpc.community/OpenHPC:/1.3/CentOS_7/aarch64/ohpc-release-1.3-1.el7.aarch64.rpm"

tf_build_noohpc_dependencies:
        - openmpi
        - openmpi-devel
        - fftw
        - fftw-devel
        - hdf5
        - hdf5-devel
        - perl-devel
        - multilib-rpm-config
        - execstack

tf_build_ohpc_dependencies:
        - lmod-ohpc
        - openmpi3-gnu8-ohpc
        - ohpc-gnu8-perf-tools
        - ohpc-buildroot
        - ohpc-gnu8-io-libs
        - ohpc-gnu8-python-libs
        - ohpc-gnu8-runtimes
        - ohpc-gnu8-serial-libs
        - ohpc-gnu8-parallel-libs
        - fftw-gnu8-openmpi3-ohpc
        - lmod-defaults-gnu8-openmpi3-ohpc

tf_build_java:
        - java-11-openjdk
        - java-11-openjdk-devel

tf_build_py3_dependencies:
        - pip
        - Cython
        - six
        - wheel
        - setuptools
        - mock
        - "future>=0.17.1"

tf_build_keras:
        - "keras_applications==1.0.6"
        - "keras_preprocessing==1.0.5"
