---
- name: Delete build dirs bazel
  file:
          path: "{{ item }}"       
          state: absent
  with_items:
          - "{{ bazel_dir_base }}"
          - "{{ bazel_dir_src }}"
          - "{{ bazel_dir_output }}"

- name: Create build dirs bazel
  file:
          path: "{{ item }}"       
          state: directory
          mode: '0755'
          owner: "{{ user }}"
          group: "{{ user }}"
  with_items:
          - "{{ bazel_dir_base }}"
          - "{{ bazel_dir_src }}"
          - "{{ bazel_dir_output }}"

- name: Fetch rpm spec for bazel
  template:
          src: "bazel.spec.j2"
          dest: "{{ bazel_dir_src }}/bazel.spec"
          owner: "{{ user }}"
          group: "{{ user }}"

- name: Build bazel
  shell: "ml unload ohpc && rpmbuild -ba {{ bazel_dir_src }}/bazel.spec"
  args:
          chdir: "{{ bazel_dir_src }}"
          executable: "/bin/bash"
  register: bazel_build_log
- debug: var=bazel_build_log

- name: Install bazel
  yum:
          name: "{{ bazel_rpm }}"
          state: present
  become: yes
  become_user: root
  become_method: sudo
