---
- name: Build tensorflow
  import_tasks: roles/tensorflow/tasks/build_tensorflow.yml
  become: yes
  become_user: "{{ user }}"
  become_method: su
  become_flags: "-s /bin/bash"

- name: Pre tests
  import_tasks: roles/tensorflow/tasks/pre_test.yml
  become: yes
  become_user: "{{ user }}"
  become_method: su
  become_flags: "-s /bin/bash"

- name: Test tensorflow
  import_tasks: roles/tensorflow/tasks/test_tensorflow.yml
  become: yes
  become_user: "{{ user }}"
  become_method: su
  become_flags: "-s /bin/bash"
