---
# Bazel variables
build_bazel: true

bazel_version: "0.26.1"
bazel_minorversion: "0"
bazel_rpm: "{{ dir_rpmbuilt }}/bazel-{{ bazel_version }}-{{ bazel_minorversion }}.{{ distribution }}.{{ arch }}.rpm"
bazel_dir_base: "{{ dir_home }}/bazel"
bazel_dir_src: "{{ bazel_dir_base }}/{{ bazel_version}}"
bazel_dir_output: "{{ bazel_dir_src }}/output"
bazel:
       release_url: "https://github.com/bazelbuild/bazel/releases/download/{{ bazel_version }}/bazel-{{ bazel_version }}-dist.zip"
       release_zip: "bazel-{{ bazel_version }}-dist.zip"
       binary: "{{ bazel_dir_output }}/bazel"
       patching_required: false

