---

# TensorFlow variables
tensorflow_version: "1.15.0"
tensorflow_dir_base: "{{ dir_home }}/tensorflow/{{ tensorflow_version}}"
tensorflow_dir_src: "{{ tensorflow_dir_base }}/tensorflow-{{ tensorflow_version }}"
tensorflow_configure: "{{ tensorflow_dir_src }}/configure"
tensorflow_dir_output: "/tmp/tensorflow_pkg"
build_tf_mpi: true
tensorflow:
       release_url: "https://github.com/tensorflow/tensorflow/archive/v{{ tensorflow_version }}.zip"
       release_zip: "tensorflow-{{ tensorflow_version }}.zip"
       wheel: "{{ tensorflow_dir_output }}/tensorflow-{{ tensorflow_version }}-cp36-cp36m-linux_{{ arch }}.whl"
       patching_required: true
       patch: 'patch_bazelbuild.patch'
       built_tarball: "tensorflow_{{ tensorflow_version }}_{{ build_id }}.tar.gz"
       cxx_optimizations:
               - "-D_GLIBCXX_USE_CXX11_ABI=0"
       c_optimizations:
               - "-funsafe-math-optimizations"
               - "-ftree-vectorize"
               - "-fomit-frame-pointer"

